services:
  - type: web
    name: cloaker4-frontend
    env: node
    buildCommand: cd frontend && yarn install && yarn build
    startCommand: cd frontend && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000