services:
  - type: web
    name: cloaker4-frontend
    env: node
    rootDir: frontend
    buildCommand: yarn install && yarn build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: NODE_ENV
        value: production